// ------------------------------------
// Constants
// ------------------------------------
export const PASSPORT_LOGIN_BEGIN      = 'PASSPORT_LOGIN_BEGIN'
export const PASSPORT_LOGIN_FAILURE    = 'PASSPORT_LOGIN_FAILURE'
export const PASSPORT_LOGIN_SUCCESS    = 'PASSPORT_LOGIN_SUCCESS'

export const PASSPORT_INITIAL_BEGIN    = 'PASSPORT_INITIAL_BEGIN'
export const PASSPORT_INITIAL_FAILURE  = 'PASSPORT_INITIAL_FAILURE'
export const PASSPORT_INITIAL_SUCCESS  = 'PASSPORT_INITIAL_SUCCESS'

export const PASSPORT_LOGINOUT_BEGIN   = 'PASSPORT_LOGINOUT_BEGIN'
export const PASSPORT_LOGINOUT_FINISH  = 'PASSPORT_LOGINOUT_FINISH' 

export const PASSPORT_EDITPWD_BEGIN    = 'PASSPORT_EDITPWD_BEGIN'
export const PASSPORT_EDITPWD_FAILURE  = 'PASSPORT_EDITPWD_FAILURE'
export const PASSPORT_EDITPWD_SUCCESS  = 'PASSPORT_EDITPWD_SUCCESS'