// ------------------------------------
// Constants
// ------------------------------------
export const ADMINS_GROUP_LIST_BEGIN      = 'ADMINS_GROUP_LIST_BEGIN'
export const ADMINS_GROUP_LIST_FAILURE    = 'ADMINS_GROUP_LIST_FAILURE'
export const ADMINS_GROUP_LIST_SUCCESS    = 'ADMINS_GROUP_LIST_SUCCESS'

export const ADMINS_GROUP_ADD_BEGIN       = 'ADMINS_GROUP_ADD_BEGIN'
export const ADMINS_GROUP_ADD_FAILURE     = 'ADMINS_GROUP_ADD_FAILURE'
export const ADMINS_GROUP_ADD_SUCCESS     = 'ADMINS_GROUP_ADD_SUCCESS'

export const ADMINS_GROUP_EDIT_BEGIN      = 'ADMINS_GROUP_EDIT_BEGIN'
export const ADMINS_GROUP_EDIT_FAILURE    = 'ADMINS_GROUP_EDIT_FAILURE'
export const ADMINS_GROUP_EDIT_SUCCESS    = 'ADMINS_GROUP_EDIT_SUCCESS'

export const ADMINS_GROUP_REMOVE_BEGIN    = 'ADMINS_GROUP_REMOVE_BEGIN'
export const ADMINS_GROUP_REMOVE_FAILURE  = 'ADMINS_GROUP_REMOVE_FAILURE'
export const ADMINS_GROUP_REMOVE_SUCCESS  = 'ADMINS_GROUP_REMOVE_SUCCESS'